import Link from "next/link";
import { AppShell } from "@/components/app-shell";
import { Badge, Card, CardHeader } from "@/components/ui";
import { listReports } from "@/lib/store/reports";

export default async function IncidentsPage() {
  const reports = await listReports();

  return (
    <AppShell>
      <h1 className="text-3xl font-semibold">Incidents</h1>
      <p className="mt-2 text-sm text-talos-muted">AI-generated Splunk investigations ready for engineering triage.</p>
      <Card className="mt-6">
        <CardHeader title="Incident Queue" detail="Open and triaged incidents generated by Talos Resolver." />
        <div className="overflow-x-auto">
          <table className="w-full min-w-[900px] text-left text-sm">
            <thead className="border-b border-talos-line text-xs uppercase tracking-[.14em] text-talos-muted">
              <tr>
                <th className="px-5 py-3">Incident ID</th>
                <th className="px-5 py-3">Service</th>
                <th className="px-5 py-3">Route</th>
                <th className="px-5 py-3">Priority</th>
                <th className="px-5 py-3">Root Cause</th>
                <th className="px-5 py-3">Status</th>
                <th className="px-5 py-3">Confidence</th>
                <th className="px-5 py-3">Time</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-talos-line">
              {reports.map((report) => (
                <tr key={report.incidentId} className="hover:bg-white/[.03]">
                  <td className="px-5 py-4 font-medium text-talos-cyan"><Link href={`/incidents/${report.incidentId}`}>{report.incidentId}</Link></td>
                  <td className="px-5 py-4">{report.affectedService}</td>
                  <td className="px-5 py-4 text-talos-muted">{report.affectedRoute}</td>
                  <td className="px-5 py-4"><Badge tone={report.priority === "critical" ? "critical" : "warn"}>{report.priority}</Badge></td>
                  <td className="max-w-md px-5 py-4 text-slate-300">{report.rootCause}</td>
                  <td className="px-5 py-4"><Badge tone="ok">{report.status}</Badge></td>
                  <td className="px-5 py-4">{report.confidence}%</td>
                  <td className="px-5 py-4 text-talos-muted">{new Date(report.createdAt).toLocaleString()}</td>
                </tr>
              ))}
            </tbody>
          </table>
          {!reports.length ? <div className="p-8 text-sm text-talos-muted">No incidents yet. Run the demo resolver from the dashboard.</div> : null}
        </div>
      </Card>
    </AppShell>
  );
}
