import Link from "next/link";
import { Siren } from "lucide-react";
import { EmptyState } from "@/components/empty-state";
import { PageHeader } from "@/components/page-header";
import { Badge, Card, CardHeader } from "@/components/ui";
import { listReports } from "@/lib/store/reports";

export default async function IncidentsPage() {
  const reports = await listReports();

  return (
    <>
      <PageHeader
        title="Incidents"
        description="AI-generated Splunk investigations ready for engineering triage."
      />

      <Card className="talos-fade-up talos-stagger-2 mt-6 overflow-hidden">
        <CardHeader title="Incident Queue" detail="Open and triaged incidents generated by Talos Resolver." />
        {reports.length ? (
          <div className="overflow-x-auto">
            <table className="w-full min-w-[900px] text-left text-sm">
              <thead className="border-b border-talos-line text-xs uppercase tracking-[.14em] text-talos-muted">
                <tr>
                  <th className="px-5 py-3">Incident ID</th>
                  <th className="px-5 py-3">Service</th>
                  <th className="px-5 py-3">Route</th>
                  <th className="px-5 py-3">Priority</th>
                  <th className="px-5 py-3">Root Cause</th>
                  <th className="px-5 py-3">Status</th>
                  <th className="px-5 py-3">Confidence</th>
                  <th className="px-5 py-3">Time</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-talos-line">
                {reports.map((report, index) => (
                  <tr
                    key={report.incidentId}
                    className="talos-row-enter transition hover:bg-white/[.03]"
                    style={{ animationDelay: `${index * 40}ms` }}
                  >
                    <td className="px-5 py-4 font-medium text-talos-cyan">
                      <Link href={`/incidents/${report.incidentId}`}>{report.incidentId}</Link>
                    </td>
                    <td className="px-5 py-4">{report.affectedService}</td>
                    <td className="px-5 py-4 text-talos-muted">{report.affectedRoute}</td>
                    <td className="px-5 py-4">
                      <Badge tone={report.priority === "critical" ? "critical" : "warn"}>{report.priority}</Badge>
                    </td>
                    <td className="max-w-md px-5 py-4 text-slate-300">{report.rootCause}</td>
                    <td className="px-5 py-4">
                      <Badge tone="ok">{report.status}</Badge>
                    </td>
                    <td className="px-5 py-4">{report.confidence}%</td>
                    <td className="px-5 py-4 text-talos-muted">{new Date(report.createdAt).toLocaleString()}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        ) : (
          <div className="p-6">
            <EmptyState
              compact
              icon={Siren}
              title="No incidents yet"
              description="Run the guided demo flow to capture a crash and generate your first AI triage report."
              action={{ label: "Open Demo Flow", href: "/demo" }}
            />
          </div>
        )}
      </Card>
    </>
  );
}
