import Link from "next/link";
import { Siren } from "lucide-react";
import { EmptyState } from "@/components/empty-state";
import { PageHeader } from "@/components/page-header";
import { Badge, Card, CardHeader } from "@/components/ui";
import { listReports } from "@/lib/store/reports";

export const dynamic = "force-dynamic";

export default async function IncidentsPage() {
  const reports = await listReports();

  return (
    <>
      <PageHeader
        title="Incidents"
        description="AI-generated Splunk investigations ready for engineering triage."
      />

      <Card className="talos-fade-up talos-stagger-2 mt-4 overflow-hidden">
        <CardHeader title="Incident Queue" detail="Open and triaged incidents generated by Talos Resolver." />
        {reports.length ? (
          <div className="overflow-x-auto">
            <table className="w-full min-w-[800px] text-left text-xs">
              <thead className="border-b border-talos-line text-[10px] uppercase tracking-[.14em] text-talos-muted">
                <tr>
                  <th className="px-3 py-2">Incident ID</th>
                  <th className="px-3 py-2">Service</th>
                  <th className="px-3 py-2">Route</th>
                  <th className="px-3 py-2">Priority</th>
                  <th className="px-3 py-2">Root Cause</th>
                  <th className="px-3 py-2">Status</th>
                  <th className="px-3 py-2">Confidence</th>
                  <th className="px-3 py-2">Time</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-talos-line text-black">
                {reports.map((report, index) => (
                  <tr
                    key={report.incidentId}
                    className="talos-row-enter transition hover:bg-[#ffe100]"
                    style={{ animationDelay: `${index * 40}ms` }}
                  >
                    <td className="px-3 py-2.5 font-medium text-talos-cyan">
                      <Link href={`/dashboard/incidents/${report.incidentId}`}>{report.incidentId}</Link>
                    </td>
                    <td className="px-3 py-2.5">{report.affectedService}</td>
                    <td className="px-3 py-2.5 text-talos-muted">{report.affectedRoute}</td>
                    <td className="px-3 py-2.5">
                      <Badge tone={report.priority === "critical" ? "critical" : "warn"}>{report.priority}</Badge>
                    </td>
                    <td className="max-w-sm px-3 py-2.5 font-bold text-black">{report.rootCause}</td>
                    <td className="px-3 py-2.5">
                      <Badge tone="ok">{report.status}</Badge>
                    </td>
                    <td className="px-3 py-2.5">{report.confidence}%</td>
                    <td className="px-3 py-2.5 text-talos-muted">{new Date(report.createdAt).toLocaleString()}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        ) : (
          <div className="p-4">
            <EmptyState
              compact
              icon={Siren}
              title="No incidents yet"
              description="Send a real SDK event and run the resolver to generate your first AI triage report."
              action={{ label: "Open Live Console", href: "/dashboard/demo" }}
            />
          </div>
        )}
      </Card>
    </>
  );
}
